from .internal.Arc                     import Arc                     as Arc                     # Part
from .internal.ArcOfCircle             import ArcOfCircle             as ArcOfCircle             # Part
from .internal.ArcOfConic              import ArcOfConic              as ArcOfConic              # Part
from .internal.ArcOfEllipse            import ArcOfEllipse            as ArcOfEllipse            # Part
from .internal.ArcOfHyperbola          import ArcOfHyperbola          as ArcOfHyperbola          # Part
from .internal.ArcOfParabola           import ArcOfParabola           as ArcOfParabola           # Part
from .internal.AttachEngine            import AttachEngine            as AttachEngine            # Attacher
from .internal.BSplineCurve            import BSplineCurve            as BSplineCurve            # Part
from .internal.BSplineSurface          import BSplineSurface          as BSplineSurface          # Part
from .internal.BezierCurve             import BezierCurve             as BezierCurve             # Part
from .internal.BezierSurface           import BezierSurface           as BezierSurface           # Part
from .internal.BodyBase                import BodyBase                as BodyBase                # Part
from .internal.Circle                  import Circle                  as Circle                  # Part
from .internal.Cone                    import Cone                    as Cone                    # Part
from .internal.Conic                   import Conic                   as Conic                   # Part
from .internal.Cylinder                import Cylinder                as Cylinder                # Part
from .internal.Ellipse                 import Ellipse                 as Ellipse                 # Part
from .internal.GeometryBoolExtension   import GeometryBoolExtension   as GeometryBoolExtension   # Part
from .internal.GeometryDoubleExtension import GeometryDoubleExtension as GeometryDoubleExtension # Part
from .internal.GeometryIntExtension    import GeometryIntExtension    as GeometryIntExtension    # Part
from .internal.GeometryStringExtension import GeometryStringExtension as GeometryStringExtension # Part
from .internal.Hyperbola               import Hyperbola               as Hyperbola               # Part
from .internal.Line                    import Line                    as Line                    # Part
from .internal.LineSegment             import LineSegment             as LineSegment             # Part
from .internal.OffsetCurve             import OffsetCurve             as OffsetCurve             # Part
from .internal.OffsetSurface           import OffsetSurface           as OffsetSurface           # Part
from .internal.Parabola                import Parabola                as Parabola                # Part
from .internal.Part2DObject            import Part2DObject            as Part2DObject            # Part
from .internal.PartFeature             import PartFeature             as Feature                 # Part
from .internal.Plane                   import Plane                   as Plane                   # Part
from .internal.PlateSurface            import PlateSurface            as PlateSurface            # Part
from .internal.Point                   import Point                   as Point                   # Part
# from .internal.Precision               import Precision               as Precision               # Base
from .internal.Sphere                  import Sphere                  as Sphere                  # Part
from .internal.SurfaceOfExtrusion      import SurfaceOfExtrusion      as SurfaceOfExtrusion      # Part
from .internal.SurfaceOfRevolution     import SurfaceOfRevolution     as SurfaceOfRevolution     # Part
from .internal.TopoShape               import TopoShape               as Shape                   # Part
from .internal.TopoShapeCompSolid      import TopoShapeCompSolid      as CompSolid               # Part
from .internal.TopoShapeCompound       import TopoShapeCompound       as Compound                # Part
from .internal.TopoShapeEdge           import TopoShapeEdge           as Edge                    # Part
from .internal.TopoShapeFace           import TopoShapeFace           as Face                    # Part
from .internal.TopoShapeShell          import TopoShapeShell          as Shell                   # Part
from .internal.TopoShapeSolid          import TopoShapeSolid          as Solid                   # Part
from .internal.TopoShapeVertex         import TopoShapeVertex         as Vertex                  # Part
from .internal.TopoShapeWire           import TopoShapeWire           as Wire                    # Part
from .internal.Toroid                  import Toroid                  as Toroid                  # Part
